### ISSUE TITLE
Less of an issue, more of a question: Could this mod be theoretically made to work as a replacement to Vanilla Core Shaders?

### ISSUE THREAD

**Issue by melechdaviid** [FoundationGames/Animatica#14]
So: I use a custom resource pack, and it turns out that the animated parts of it don't work with Sodium. What I'm wondering is, could this mod be made to trick the resource pack textures, that usually use Minecraft's own core shaders, to function with Animatica instead when Sodium is installed?

**Comment by FoundationGames** [comment]
No, it cannot
(core shaders reprogram the rendering pipeline to make animations work, there is no **single** way to just automatically convert that to animatica/optifine since it can be done in an *infinite number of different ways*)
