### ISSUE TITLE
Optifine custom GUI

### ISSUE THREAD

**Issue by opekope2** [FoundationGames/Animatica#15]
I created a mod called [OptiGUI](https://github.com/opekope2/OptiGUI), which adds support for OptiFine custom GUIs in Fabric. It uses the Optifine format so no converter is needed.

It is fully compatible with Animatica as of opekope2/OptiGUI@b174ec0bb43c429c9fae95bc0e8ab1a9fcb3de04, thanks for this awesome mod.

Please consider mentioning it in README.

**Comment by RaptaG** [comment]
Added
