### ISSUE TITLE
Compat?

### ISSUE THREAD

**Issue by itsdinkd** [FoundationGames/Animatica#2]
Does this work with Fresh Animations resource pack? And will there b e any issues if I use fabric CTM mod?

**Comment by FoundationGames** [comment]
Read the mod page, and there should be no issues with CTM

**Comment by itsdinkd** [comment]
I did read the modpage, hence me asking here..... Nowhere does it state that it works with fresh animations. All I learned from your mod page is that there are two CTM types, OptiFine/MCPatcher and Fabric's CTM mod. Which btw, your page doesn't say which one its compatible with.

**Comment by FoundationGames** [comment]
![image](https://user-images.githubusercontent.com/43485105/135960101-7f8df5a7-fd87-43b8-8b7a-f3062ce27ed6.png)
If you check Fresh Animations's mod page, it also says that it doesn't **YET** work with the Fabric CEM mod

**Comment by red2blue** [comment]
yeah I'm not a dev I didn't know CEM meant your mod. cocky asshole
developer #10 nice to meet ya.
