### ISSUE TITLE
Memory usage exception

### ISSUE THREAD

**Issue by duakc** [FoundationGames/Animatica#38]
English
my english is not good,if there are any mistake.I apologize
## Reproduce
download https://www.curseforge.com/minecraft/texture-packs/cute-mob-models-resource-pack
install [Animatica](https://github.com/FoundationGames/Animatica) mod in minecraft
make the resourcepack to enable
## Except
The resourcepack will be load normal
## In Fact
the memory will increase crazily ! Until I use the task manager to shutdown it.

## Other Information
os:windows10
memory size:16g
log :https://pastebin.com/Y4ugHG9K
miecraft version:1.18.2
mod version:0..5
resourcepack version:1.1[1.18.1~1.18.2]

Chinese
## 复现
下载材质包：https://www.curseforge.com/minecraft/texture-packs/cute-mob-models-resource-pack
安装 [Animatica](https://github.com/FoundationGames/Animatica) mod 在 minecraft 中
启用材质包
## 期望
这个材质包会正常的加载成功
## 实际
内存使用量暴涨，直到我用任务管理器去关闭

## 其他信息
os:windows10
memory size:16g
log :https://pastebin.com/Y4ugHG9K
miecraft version:1.18.2
mod version:0..5
resourcepack version:1.1[1.18.1~1.18.2]

**Comment by Madis0** [comment]
Can confirm on [Fabulously Optimized 4.6.1](https://legacy.curseforge.com/minecraft/modpacks/fabulously-optimized/files/4477834): [latest.log](https://github.com/FoundationGames/Animatica/files/11790848/latest.log)
I've had at least one other user who could also confirm it (logs https://mclo.gs/c9pQmHo) and 3 users who could not confirm it, so I don't know what the actual cause might be... GPU?

**Comment by Madis0** [comment]
Confirmed fixed on v0.6.
