### ISSUE TITLE
Incompatibility with Legendary Tooltips mod armor preview.

### ISSUE THREAD

**Issue by MbtMarco** [FoundationGames/Animatica#42]
### 1.20.1 - Animatica v0.6
<img width="1440" alt="Screenshot 2023-07-21 alle 16 55 49" src="https://github.com/FoundationGames/Animatica/assets/124934175/9b897871-0968-4f8e-9763-6f6259e63570">

### What should be viewed instead:
![](https://i.imgur.com/TJfJlnx.gif)

**Comment by IntM4rco** [comment]
1.20.1 - Animatica v0.6

**Comment by MbtMarco** [comment]
Not an Animatica issue
