### ISSUE TITLE
Animating Enchantment Glint

### ISSUE THREAD

**Issue by BenKenobie31415** [FoundationGames/Animatica#50]
I have a resourcepack that adds a custom animation for the enchantment_glint.
It worked on 1.19.1 just fine but seems to be broken since 1.19.4 but I couldn't find any change log or similar explaining why this is.
My resourcepack simply contains a glint.png and a glint.properties under assets->minecraft->optifine->anim and the glint texture to replace.

```
# Custom animation
from=./glint.png
to=textures/misc/enchanted_item_glint.png
x=0
y=0
w=16
h=16
duration=8
interpolate=true
```

**Comment by FoundationGames** [comment]
Does your animation work with OptiFine?

**Comment by BenKenobie31415** [comment]
Just tested, no it does not work with optifine, but I just can't figure out why.
The Optifine Documentation doesn't seem to have changed in a while and my pack should be working as far as i can tell from the Optifine Documentation.
So I guess it is not an issue with this mod.
But still, any idea, what could cause that change between 1.19.1 and 1.19.4?

**Comment by BenKenobie31415** [comment]
So I tested some more.
I assume the problem had to do with the custom namespace of the folder in which the texture was.
So I moved the texture from the anim-folder to the location of the default glint and now it is working.
Sorry for the inconvenience :(
