### ISSUE TITLE
Does not appear to work with textures used in CIT Resewn

### ISSUE THREAD

**Issue by jpeterik12** [FoundationGames/Animatica#7]
CIT Resewn allows for the changing of item textures using The MCPatcher format. It would be nice if this mod worked with that one to allow for animated armor using both CIT and animations

**Comment by FoundationGames** [comment]
Animatica should be able to animate *any* texture, except for blocks and items (you should be using the vanilla format)
There should be no reason that it doesn't work with CIT armor textures, if you could provide more information that would help

**Comment by jpeterik12** [comment]
Turns Out I'm just bad at spelling file names. Thanks for the mod!
