### ISSUE TITLE
Animation sequence incorrect

### ISSUE THREAD

**Issue by QuPlexion** [FoundationGames/Animatica#8]
I'm making a resource pack that has animated netherite armor and it seems like the animation sequence isn't what it should be. The properties file is as follows:

> from=./netherite_layer_1.png
> to=textures/models/armor/netherite_layer_1.png
> x=0
> y=0
> w=64
> h=32
> interpolate=false
> tile.0=0
> duration.0=40
> 
> tile.1=1
> duration.1=150
> 
> tile.2=2
> duration.2=90
> 
> tile.3=3
> duration.3=90
> 
> tile.4=4
> duration.4=150
> 
> tile.5=5
> duration.5=40
> 
> tile.6=4
> duration.6=150
> 
> tile.7=3
> duration.7=90
> 
> tile.8=2
> duration.8=90
> 
> tile.9=1
> duration.9=150

(the texture is 64x192 so 6 different frames)

But the animation in games seems to go in this order instead:
_frame 5 (tile.5) > frame 4 (tile.4 or tile.6) > frame 3 (tile.3 or tile.7) > frame 2 (tile.2 or tile.8) > frame 1 (tile.1 or tile.9) > frame 0(tile.0)_

Not sure if I am misunderstanding or doing something wrong or if this is a bug

**Comment by FoundationGames** [comment]
This appears to be a known bug, will be worked on for the next release for both 1.17 and 1.18

**Comment by FoundationGames** [comment]
(has been fixed for a while)
